config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'talks#index'
  resources :users
post 'users/:user_id/friendships'  => 'friendships#create' , as: 'friendships_create'
get 'friendships/:id/rooms'  => 'rooms#create' , as: 'rooms_create'
get 'rooms/:id/talks'  => 'talks#show' , as: 'talks_show'
post 'rooms/:id/talks/post' => 'talks#post'

  resources :friendships
  resources :rooms
#   scope shallow_prefix: "sekret" do
#   resources :users do
#     resources :friendships, shallow: true
#   end
# end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :from_user, :class_name => 'User'
  belongs_to :to_user, :class_name => 'User'
  has_one :room, dependent: :destroy
   scope :search_with_from_id, ->(id) { where(from_user_id: id) }
   scope :search_with_to_id, ->(id) { where(to_user_id: id) }

end

app/models/room.rb
class Room < ActiveRecord::Base
    belongs_to :friendship
    has_many :talks, dependent: :destroy
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  belongs_to :room
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :talks
  has_many :friendships_of_from_user, :class_name => 'Friendship', :foreign_key => 'from_user_id', :dependent => :destroy
  has_many :friendships_of_to_user, :class_name => 'Friendship', :foreign_key => 'to_user_id', :dependent => :destroy
  has_many :friends_of_from_user, :through => :friendships_of_from_user, :source => 'to_user'
  has_many :friends_of_to_user, :through => :friendships_of_to_user, :source => 'from_user'
  def friends
    friends_of_from_user+friends_of_to_user
  end

  def friendships
    friendships_of_from_user+friendships_of_to_user
  end

  has_attached_file :avatar, styles: { medium: "150x150>", thumb: "50x50>" }
  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :uniqueid, :avatar])
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

    def index
      @user = current_user
      @friendships = @user.friends
      render "friendship-index.js.erb"
    end

    def show
       @user = User.find(params[:id])
       render "friendship-show.js.erb"
    end

    def destroy
        @friendship = Friendship.search_with_to_id(current_user.id).search_with_from_id(params[:id])
        if @friendship.empty?
          @friendship = Friendship.search_with_to_id(params[:id]).search_with_from_id(current_user.id)
        end
        Friendship.destroy(@friendship)
        redirect_to :root
    end

    def create
      @friendship = Friendship.new(to_user_id: params[:user_id], from_user_id: current_user.id)
      @friendship.save
       redirect_to :root
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    def index
      @a = Room.joins(:friendship).merge(Friendship.where(from_user_id: current_user.id))
      @b = Room.joins(:friendship).merge(Friendship.where(to_user_id: current_user.id))
      @rooms = @a+@b
      render "room-index.js.erb"
    end

    def create
      @friendship = Friendship.search_with_to_id(current_user.id).search_with_from_id(params[:id])
      if @friendship.empty?
        @friendship = Friendship.search_with_to_id(params[:id]).search_with_from_id(current_user.id)
      end
      @room = Room.new(friendship_id: @friendship.ids[0].to_i)
      @room.save
      Talk.create(room_id: @room.id, message: nil)
      redirect_to :root
    end

end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
   before_action :authenticate_user!, only:[:index]

    def index
      @a = Room.joins(:friendship).merge(Friendship.where(from_user_id: current_user.id))
      @b = Room.joins(:friendship).merge(Friendship.where(to_user_id: current_user.id))
      @rooms = @a+@b
    end

    def show
      config_pusher = YAML.load_file('config/pusher.yml')[Rails.env]
      @pusher_access_key = config_pusher['access_key']
      @talks = Talk.where(room_id: params[:id])
      render "talk-show.js.erb"
    end

    def post
      @talk = Talk.new(create_params)
      @talk.save
      time = view_context.simple_time(@talk.created_at)
      Pusher.trigger( params[:room_id]+'_channel', 'chat_event', {
        message: params[:message], sender_id: params[:sender_id], created_at: time
      })
      render :text => 'OK', :status => 200
    end

    def create_params
      params.permit(:message, :room_id, :sender_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # protect_from_forgery except: :show
    def index
      @users = User.all.where.not(id: current_user.id)
      render "user-index.js.erb"
    end

    def show
     @user = User.find(params[:id])
     render "user-show.js.erb"
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def findroom(id)
    @friendship = Friendship.search_with_to_id(current_user.id).search_with_from_id(id)
      if @friendship.empty?
          @friendship = Friendship.search_with_to_id(id).search_with_from_id(current_user.id)
      end
      @room = Room.where(friendship_id: @friendship[0].id)
      if @room.empty?
        return true
      else
        return false
      end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
    def finduser(id)
      @room = Room.find(id)
      @friendship = Friendship.find(@room.friendship_id)
      if @friendship.from_user_id == current_user.id
          @user = User.find(@friendship.to_user_id )
      else
          @user = User.find(@friendship.from_user_id )
      end
      return @user
    end
end

app/helpers/talks_helper.rb
module TalksHelper
  def simple_time(time)
    time.strftime("%H:%M")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def friendship_method(id)
      @friendship = Friendship.search_with_to_id(current_user.id).search_with_from_id(id)
      if @friendship.empty?
        @friendship = Friendship.search_with_to_id(id).search_with_from_id(current_user.id)
      end
      if @friendship.empty?
        return true
      else
      return false
      end
  end
end

app/views/friendships/_index.html.erb
<%= link_to friendship_path(friendship.id) ,remote: true do %>
  <li class="talk-room">
    <div class="talk-room-detail">
      <div class="user-image">
        <%= image_tag friendship.avatar.url(:thumb) ,class: "user-thumb" %>
      </div>
      <div class="user-info">
        <div class="user-name"><%= friendship.name %></div>
      </div>
    </div>
  </li>
<% end %>

app/views/friendships/_show.html.erb
<div class="friend-info">
  <div class="friend-info-top">
    <div class="friend-info-avatar">
      <%= image_tag user.avatar.url(:medium), class: "user-medium" %>
    </div>
    <div class="friend-info-name">
      <P><%= user.name %></P>
    </div>
  </div>
  <div class="friend-info-down">
    <% if findroom(user.id) %>
      <div class="friend-info-add">
        <%= link_to "トーク", rooms_create_path(user) %>
      </div>
    <% end %>
      <div class="friend-info-block">
        <%= link_to "ブロック", friendship_path(user.id) , method: :delete %>
      </div>
  </div>
</div>

app/views/friendships/friendship-index.js.erb
$('#friend-list').html("<%= j(render partial: 'friendships/index', collection: @friendships, as: 'friendship') %>");
$('#outer-right').empty();

app/views/friendships/friendship-show.js.erb
$('#outer-right').html("<%= j(render partial: 'friendships/show', locals: { user: @user}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.pusher.com/4.0/pusher.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/rooms/_index.html.erb
<%= link_to talks_show_path(room.id) ,class: 'talk-room-ajax', remote: true do %>
  <li class="talk-room">
    <%= hidden_field_tag 'room_id', room.id , class: "room_id"%>
    <div class="talk-room-detail">
      <div class="user-image">
        <%= image_tag finduser(room.id).avatar.url(:thumb) ,class: "user-thumb" %>
      </div>
      <div class="user-info">
        <div class="user-name"><%= finduser(room.id).name %></div>
        <div class="last-talk"><%= room.talks.last.message%></div>
      </div>
      <div class="date"><%= simple_time(room.talks.last.created_at)%></div>
      <div class="talk-count"></div>
    </div>
  </li>
<% end %>

app/views/rooms/room-index.js.erb
$('#room-list').empty();
$('#room-list').html("<%= j(render partial: 'rooms/index', collection: @rooms, as: 'room') %>");
$('#outer-right').empty();

app/views/talks/_show.html.erb
<%=  form_tag('rooms/:id/talks/post', :remote => true) do %>
<div class="talk-user">
  <div class="talk-user-image"><%= image_tag finduser(talks[0].room.id).avatar.url(:thumb), class: "user-thumb" %></div>
  <div class="talk-user-name"><%= finduser(talks[0].room.id).name %></div>
  <div class="talk-session" id="talk-session-id">
<!-- <div class="talk-session-date"> -->
  <!-- <div class="session-date"><p>3月23日</p></div> -->
    <% talks.each do |talk| %>
      <%= hidden_field_tag 'room_id', talk.room.id %>
      <% if !(talk.sender_id == current_user.id) && !(talk.nil?)%>
        <div class="talk-session-you">
          <p class="talk-content-you"><%= talk.message %></p>
          <div><%= simple_time(talk.created_at) %></div>
        </div>
      <% elsif talk.sender_id == current_user.id && !(talk.nil?)%>
        <div class="talk-session-me">
          <p class="talk-content-me"><%= talk.message %></p>
          <span><%= simple_time(talk.created_at) %></span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<div class="talk-text">
  <%= hidden_field_tag 'sender_id', current_user.id %>
  <%= text_field_tag 'message' %>
  <%= submit_tag 'send',id: 'send'%>
<% end %>
</div>
  <script>
    var pusher = new Pusher('<%= @pusher_access_key %>');
  </script>

app/views/talks/index.html.erb
<header>
  <div class="head-outer">
    <div class="icon">
      LINE
    </div>
    <div class="user">
      <p class="name"><%= current_user.name %></p>
    </div>
    <div class="sankaku"></div>
    <div class="info">
      <ul>
        <li>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        </li>
        <li>
          <%= link_to '編集', edit_user_registration_path %>
        </li>
        <li>
        </li>
      </ul>
    </div>
  </div>
</header>
<div clss="container">
  <div class="main-outer">
    <div class="outer-left">
      <div class="search-form">
        <input class="input-search" type="text" placeholder="トークルームを検索する">
      </div>
      <div class="talk-list">
        <ul class="content">
          <li>
            <ul class="talklist" id="room-list" >
             <%= render partial: 'rooms/index', collection: @rooms ,as: 'room'%>
            </ul>
          </li>
          <li class="hide">
            <ul class="talklist" id="friend-list">
              <%= render partial: 'friendships/index', collection: @friendships ,as: 'friendship'%>
            </ul>
          </li>
          <li class="hide">
            <ul class="talklist" id="user-list">
              <%= render partial: 'users/index', collection: @users , as: 'user'%>
            </ul>
          </li>
        </ul>
      </div>
      <div class="talk-tab">
        <ul class="talk-tab-ul tab">
          <li class="talk-tab-li select">
            <%= link_to 'トーク',rooms_path ,remote: true %>
          </li>
          <li class="talk-tab-li" >
            <%= link_to 'フレンド',friendships_path ,remote: true %>
          </li>
          <li class="talk-tab-li">
            <%= link_to 'ユーザー',users_path , remote: true %>
          </li>
        </ul>
      </div>
    </div>
    <div class="outer-right" id="outer-right">
      <% if request.xhr? %>
        <%= render partial: 'talks/show', locals: { talks: @talks} %>
        <%= render partial: 'users/show', locals: { user: @user} %>
        <%= render partial: 'friendships/show',  locals: { user: @user} %>
      <% end %>
    </div>
  </div>
</div>

app/views/talks/talk-show.js.erb
$('#outer-right').html("<%= j(render partial: 'talks/show', locals: {talks: @talks} )%>");

$('.talk-room-ajax').on('ajax:success', function(){
        // var index = $('.tab li').index(this);
        var index = $('.talk-room-ajax').index(this);
        var aa = $('.room_id').eq(index).val();


    var pusher = new Pusher('<%= @pusher_access_key %>',{
        cluster: 'ap1',
      encrypted: true
    });

    var channel = pusher.subscribe(aa+'_channel');
    console.log(channel);

    channel.bind('chat_event', function(data) {
        console.log(data);
        var my_id = $('#sender_id').val();

        var messagelog = document.getElementById('talk-session-id');
        var messagediv = document.createElement('div');
        messagediv.className = data.sender_id === my_id ? 'talk-session-me' : 'talk-session-you';
        var paragraphElement = document.createElement("p");
        paragraphElement.className = data.sender_id === my_id ? 'talk-content-me' : 'talk-content-you';
        var textNode = document.createTextNode(data.message);
        paragraphElement.appendChild(textNode);

        var spanElement = document.createElement("span");
        var timeNode = document.createTextNode(data.created_at);
        spanElement.appendChild(timeNode);

        messagediv.appendChild(paragraphElement);
        messagediv.appendChild(spanElement);
        messagelog.appendChild(messagediv);

        $('#talk-session-id').animate({scrollTop: $('#talk-session-id')[0].scrollHeight}, 'fast');

    });
});

app/views/users/_index.html.erb
<%= link_to user_path(user.id) ,remote: true do %>
<li class="talk-room">
  <div class="talk-room-detail">
    <div class="user-image">
    <%= image_tag user.avatar.url(:thumb) ,class: "user-thumb" %>
    </div>
    <div class="user-info">
      <div class="user-name"><%= user.name %></div>
    </div>
  </div>
</li>
<% end %>

app/views/users/_show.html.erb
<div class="friend-info">
  <div class="friend-info-top">
    <div class="friend-info-avatar">
      <%= image_tag user.avatar.url(:medium), class: "user-medium" %>
    </div>
    <div class="friend-info-name">
      <P><%= user.name %></P>
    </div>
    </div>
    <% if friendship_method(user.id) %>
      <div class="friend-info-down">
        <div class="friend-info-add">
          <%= link_to "友達追加", friendships_create_path(user), method: :post %>
        </div>
    <% else %>
      <div class="friend-info-block">
        <%= link_to "ブロック", friendship_path(user.id) , method: :delete %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/user-index.js.erb
$('#user-list').html("<%= j(render partial: 'users/index', collection: @users, as: 'user') %>");
$('#outer-right').empty();

app/views/users/user-show.js.erb
$('#outer-right').html("<%= j(render partial: 'users/show', locals: { user: @user}) %>");